import type {
  APIWorkspaceCreatedResponse,
  ApplicationId,
  RESTPostAPIWorkspaceJSONBody,
  UserId,
  WorkspaceId,
  WorkspaceInviteGroup,
} from "@squarecloud/api-types/v2";

import { assertString } from "@/assertions/literal";
import { Routes } from "@/lib/routes";
import { Workspace } from "@/structures";

import type { SquareCloudAPI } from "..";

export class WorkspacesModule {
  constructor(public readonly client: SquareCloudAPI) {}

  /**
   * Lists every workspace where the authenticated user is owner or member
   */
  async list(): Promise<Workspace[]> {
    const { response } = await this.client.api.request(
      Routes.workspaces.list(),
    );

    return response.map((workspace) => new Workspace(this.client, workspace));
  }

  /**
   * Fetches a workspace by ID. The user must be owner or member.
   *
   * @param workspaceId - Workspace identifier (40 hex chars or UUID v4 without hyphens)
   */
  async fetch(workspaceId: string): Promise<Workspace> {
    assertString(workspaceId, "WORKSPACE_ID");

    const { response } = await this.client.api.request(
      Routes.workspaces.info(workspaceId),
    );

    return new Workspace(this.client, response);
  }

  /**
   * Creates a new workspace owned by the authenticated user.
   * - Available only on Standard, Pro and Enterprise plans.
   *
   * @param options - The workspace name (1-32 chars)
   */
  async create(
    options: RESTPostAPIWorkspaceJSONBody,
  ): Promise<APIWorkspaceCreatedResponse> {
    assertString(options.name, "WORKSPACE_NAME");

    const { response } = await this.client.api.request(
      Routes.workspaces.create(),
      { method: "POST", body: options },
    );

    return response;
  }

  /**
   * Deletes a workspace owned by the authenticated user.
   *
   * @param workspaceId - The workspace ID
   */
  async delete(workspaceId: string): Promise<boolean> {
    assertString(workspaceId, "WORKSPACE_ID");

    const data = await this.client.api.request(Routes.workspaces.delete(), {
      method: "DELETE",
      body: { workspaceId: workspaceId as WorkspaceId },
    });

    return data?.status === "success";
  }

  /**
   * Leaves a workspace the authenticated user belongs to.
   * - The owner cannot leave their own workspace; use {@link delete} instead.
   *
   * @param workspaceId - The workspace ID
   */
  async leave(workspaceId: string): Promise<boolean> {
    assertString(workspaceId, "WORKSPACE_ID");

    const data = await this.client.api.request(Routes.workspaces.leave(), {
      method: "DELETE",
      body: { workspaceId: workspaceId as WorkspaceId },
    });

    return data?.status === "success";
  }

  /**
   * Generates a short-lived (5 min) invite code bound to the authenticated user.
   * A workspace owner can then add the user via {@link WorkspaceMembersModule.add}.
   */
  async generateInviteCode(): Promise<string> {
    const { response } = await this.client.api.request(
      Routes.workspaces.members.inviteCode(),
    );

    return response.code;
  }
}

export class WorkspaceMembersModule {
  constructor(public readonly workspace: Workspace) {}

  /**
   * Adds a member to the workspace using an invite code
   *
   * @param code - Invite code generated by {@link WorkspacesModule.generateInviteCode}
   * @param group - Permission tier for the new member
   * @returns `true` for success
   */
  async add(code: string, group: WorkspaceInviteGroup): Promise<boolean> {
    assertString(code, "INVITE_CODE");
    assertString(group, "MEMBER_GROUP");

    const data = await this.workspace.client.api.request(
      Routes.workspaces.members.add(),
      {
        method: "POST",
        body: { workspaceId: this.workspace.id as WorkspaceId, code, group },
      },
    );

    return data?.status === "success";
  }

  /**
   * Updates a member's role
   *
   * @param memberId - The member's user ID
   * @param group - New permission tier
   * @returns `true` for success
   */
  async update(
    memberId: string,
    group: WorkspaceInviteGroup,
  ): Promise<boolean> {
    assertString(memberId, "MEMBER_ID");
    assertString(group, "MEMBER_GROUP");

    const data = await this.workspace.client.api.request(
      Routes.workspaces.members.update(),
      {
        method: "PATCH",
        body: {
          workspaceId: this.workspace.id as WorkspaceId,
          memberId: memberId as UserId,
          group,
        },
      },
    );

    return data?.status === "success";
  }

  /**
   * Removes a member from the workspace.
   * - Only the workspace owner can call this.
   *
   * @param memberId - The member's user ID
   * @returns `true` for success
   */
  async remove(memberId: string): Promise<boolean> {
    assertString(memberId, "MEMBER_ID");

    const data = await this.workspace.client.api.request(
      Routes.workspaces.members.remove(),
      {
        method: "DELETE",
        body: {
          workspaceId: this.workspace.id as WorkspaceId,
          memberId: memberId as UserId,
        },
      },
    );

    return data?.status === "success";
  }
}

export class WorkspaceApplicationsModule {
  constructor(public readonly workspace: Workspace) {}

  /**
   * Shares an application owned by the authenticated user into the workspace.
   *
   * @param appId - The application ID (24 hex chars)
   * @returns `true` for success
   */
  async add(appId: string): Promise<boolean> {
    assertString(appId, "APP_ID");

    const data = await this.workspace.client.api.request(
      Routes.workspaces.applications.add(),
      {
        method: "POST",
        body: {
          workspaceId: this.workspace.id as WorkspaceId,
          appId: appId as ApplicationId,
        },
      },
    );

    return data?.status === "success";
  }

  /**
   * Removes a shared application from the workspace.
   * - Only the workspace owner can call this.
   *
   * @param appId - The application ID
   * @returns `true` for success
   */
  async remove(appId: string): Promise<boolean> {
    assertString(appId, "APP_ID");

    const data = await this.workspace.client.api.request(
      Routes.workspaces.applications.remove(),
      {
        method: "DELETE",
        body: {
          workspaceId: this.workspace.id as WorkspaceId,
          appId: appId as ApplicationId,
        },
      },
    );

    return data?.status === "success";
  }
}
